services:
  api:
    image: ghcr.io/firecrawl/firecrawl
    restart: unless-stopped
    environment:
      - SERVICE_URL_FIRECRAWL_3002
      - HOST=0.0.0.0
      - PORT=3002
      - ENV=local
    expose:
      - "3002"