services:
  forgejo:
    image: 'codeberg.org/forgejo/forgejo:16'
    restart: unless-stopped

    environment:
      - SERVICE_URL_FORGEJO_3000
      - 'FORGEJO__server__ROOT_URL=${SERVICE_URL_FORGEJO}'

      - 'FORGEJO__migrations__ALLOWED_DOMAINS=${FORGEJO__migrations__ALLOWED_DOMAINS}'
      - 'FORGEJO__migrations__ALLOW_LOCALNETWORKS=${FORGEJO__migrations__ALLOW_LOCALNETWORKS:-false}'

      - 'USER_UID=${USER_UID:-1000}'
      - 'USER_GID=${USER_GID:-1000}'

      - 'FORGEJO__database__DB_TYPE=${FORGEJO_DB_TYPE:-postgres}'
      - 'FORGEJO__database__HOST=${FORGEJO_DB_HOST}'
      - 'FORGEJO__database__NAME=${FORGEJO_DB_NAME}'
      - 'FORGEJO__database__USER=${FORGEJO_DB_USER}'
      - 'FORGEJO__database__PASSWD=${FORGEJO_DB_PASSWORD}'

    volumes:
      - '/service-data/forgejo:/data'
      - 'forgejo-timezone:/etc/timezone:ro'
      - 'forgejo-localtime:/etc/localtime:ro'

    ports:
      - '22222:22'

    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:3000'
      interval: 2s
      timeout: 10s
      retries: 15

  docker-in-docker:
    image: docker:dind
    container_name: docker_dind
    privileged: true
    command:
      - dockerd
      - -H
      - tcp://0.0.0.0:2375
      - --tls=false
    restart: unless-stopped

    volumes:
      - '/service-data/forgejo/runner/docker:/var/lib/docker'

  runner:
    image: 'data.forgejo.org/forgejo/runner:13'
    container_name: runner
    restart: unless-stopped

    depends_on:
      docker-in-docker:
        condition: service_started
      forgejo:
        condition: service_healthy

    environment:
      - DOCKER_HOST=tcp://docker-in-docker:2375

    user: '1001:1001'

    volumes:
      - '/service-data/forgejo/runner:/data'

    working_dir: /data

    command:
      - forgejo-runner
      - daemon
      - --config
      - runner-config.yml

volumes:
  forgejo-timezone:
  forgejo-localtime: